import React,{useEffect,useState} from 'react';
import {View,Text,Modal,ScrollView} from 'react-native';
import apiService from '../services/apiService';
import {MaterialSelector,Action,Field,money,s} from './ChargeableMaterials';
export default function CommercialEditor({appointmentId,requestId,onClose,onSaved}) {
 const [record,setRecord]=useState(null),[net,setNet]=useState(''),[vat,setVat]=useState('24'),[materials,setMaterials]=useState([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[catalog,setCatalog]=useState([]);
 useEffect(()=>{(async()=>{const [r,c]=await Promise.all([apiService.commercialAppointment(appointmentId),apiService.commercialCatalog()]);if(!r.success){setError(r.error);return;}setRecord(r);setCatalog(c.items||[]);const line=r.terms.lines.find(l=>l.kind==='service');setNet((line.netCents/100).toFixed(2));setVat(String(line.vatBasisPoints/100));setMaterials(r.terms.lines.filter(l=>l.kind==='material').map(l=>({itemId:l.key,quantity:Number(l.quantity)})));})();},[appointmentId]);
 async function save(){setBusy(true);setError('');try{const r=await apiService.commercialSave(appointmentId,{expectedRevision:record.revision,serviceNetPrice:net.replace(',','.'),serviceVatPercent:vat.replace(',','.'),materials,businessNote:note,...(requestId?{requestId}: {})});if(!r.success)throw Error(r.error);onSaved?.();onClose();}catch(e){const messages={PRICE_CHANGED_REFRESH_AND_RETRY:'Το ποσό άλλαξε. Κλείστε και ανοίξτε ξανά τη φόρμα.',PAID_CHARGE_REQUIRES_REFUND_RECONCILIATION:'Η αλλαγή επηρεάζει ήδη εισπραγμένο ποσό ή ΦΠΑ. Χρειάζεται τακτοποίηση επιστροφής πριν μειωθεί η χρέωση.',LEGACY_COMPLETION_REQUIRES_ACCOUNT_RECONCILIATION:'Παλιά ολοκλήρωση χωρίς καταγεγραμμένη εκκαθάριση. Απαιτείται συμφωνία λογαριασμού.'};setError(messages[e.message]||e.message);}finally{setBusy(false);}}
 const materialsCents=materials.reduce((sum,m)=>{const old=record?.terms.lines.find(l=>l.key===m.itemId),item=catalog.find(i=>i.id===m.itemId);const unit=old?.unitNetCents??Number(item?.unit_net_cents||0),rate=old?.vatBasisPoints??Number(item?.vat_basis_points||0),net=unit*Number(m.quantity||0);return sum+net+Math.round(net*rate/10000);},0);
 const serviceNet=Math.round(Number(net.replace(',','.'))*100),gross=serviceNet+Math.round(serviceNet*Number(vat.replace(',','.'))/100)+materialsCents;
 return <Modal visible transparent onRequestClose={()=>!busy&&onClose()}><View style={s.overlay}><ScrollView style={s.dialog} keyboardShouldPersistTaps="handled"><Text style={s.title}>Χρέωση ραντεβού</Text>{record&&<><Field label="Καθαρή τιμή υπηρεσίας (€)" value={net} onChangeText={setNet} keyboardType="decimal-pad"/><Field label="ΦΠΑ υπηρεσίας (%)" value={vat} onChangeText={setVat} keyboardType="decimal-pad"/><MaterialSelector value={materials} onChange={setMaterials} snapshotLines={record.terms.lines}/><Text style={s.title}>Συνολικό ποσό: {money(gross)}</Text><Field label="Σχόλιο Επιχείρησης" value={note} onChangeText={setNote} multiline maxLength={4000}/><Text>Οι σημειώσεις και οι μετρήσεις του τεχνικού διατηρούνται.</Text></>}{!!error&&<Text style={{color:'#b00'}}>{error}</Text>}<Action label={requestId?'Αποδοχή και αποθήκευση':'Αποθήκευση'} disabled={busy||!record} onPress={save}/><Action label="Άκυρο" disabled={busy} onPress={onClose}/></ScrollView></View></Modal>;
}
